#!/usr/bin/env node
/**
 * Builds the compact marks in public/icons/ (the smallest form of each logo) and the list
 * of which ids have one. Run: node scripts/build-icons.mjs
 *
 * An icon is the real logo file from svgl.app where that is the better one, otherwise a
 * simple-icons glyph in the brand colour, otherwise an existing symbol-only file in
 * public/logos/. Anything left over falls back to its lockup.
 */
import * as si from "simple-icons";
import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";

/** mark id -> simple-icons name (without the "si" prefix) */
const simple = {
  google: "Google", anthropic: "Anthropic", twitch: "Twitch", netflix: "Netflix", vercel: "Vercel", bun: "Bun",
  dropbox: "Dropbox", convex: "Convex", cloudflare: "Cloudflare", youtube: "Youtube", sst: "Sst", neon: "Neon",
  databricks: "Databricks", expo: "Expo", spacex: "Spacex", ycombinator: "Ycombinator", meta: "Meta", cursor: "Cursor",
  paypal: "Paypal", tesla: "Tesla", x: "X", baidu: "Baidu", basecamp: "Basecamp", stripe: "Stripe", shopify: "Shopify",
  figma: "Figma", replit: "Replit", nvidia: "Nvidia", deno: "Deno", netlify: "Netlify", planetscale: "Planetscale",
  remix: "Remix", tanstack: "Tanstack", uber: "Uber", airbnb: "Airbnb", linear: "Linear",
  redis: "Redis", sentry: "Sentry", guardian: "Theguardian", apple: "Apple", brave: "Brave", mozilla: "Mozilla",
  perplexity: "Perplexity", temporal: "Temporal", vite: "Vite", vitest: "Vitest", svelte: "Svelte",
  typescript: "Typescript", neovim: "Neovim", nodejs: "Nodedotjs", django: "Django", flask: "Flask", ghostty: "Ghostty",
  terraform: "Terraform", trpc: "Trpc", react: "React", nextjs: "Nextdotjs", solid: "Solid", effect: "Effect", opencode: "Opencode",
  epicgames: "Epicgames", hashicorp: "Hashicorp", github: "Github",
};

/**
 * mark id -> svgl.app title. These are the logos' own files, used as published, so they keep
 * their real colours. It covers what simple-icons lacks, and it wins where a brand's real logo
 * has more than one colour (Google, Convex, Figma) which a single-colour icon would flatten.
 */
const svgl = {
  google: "Google", convex: "Convex", figma: "Figma", dropbox: "Dropbox", paypal: "PayPal", neovim: "Neovim",
  nodejs: "Node.js", ghostty: "Ghostty", mozilla: "Firefox", trpc: "tRPC", redis: "Redis",
  cloudflare: "Cloudflare", django: "Django", youtube: "YouTube", meta: "Meta",
  microsoft: "Microsoft", openai: "OpenAI", amazon: "Amazon", sourcegraph: "Sourcegraph", twitter: "Twitter",
  eventbrite: "Eventbrite", vue: "Vue", openclaw: "OpenClaw", oxc: "Oxc", rolldown: "Rolldown", xai: "xAI",
  coinbase: "Coinbase", cluely: "Cluely", anduril: "Anduril", joyent: "Joyent", libgdx: "libGDX",
};

/** Files in public/logos that are already a symbol on their own. */
const existing = ["t3", "nytimes", "earendil", "million", "voidzero", "mit"];

/** Dark brand colours vanish on black, so they become the page's off-white. */
function ink(hex) {
  const n = Number.parseInt(hex, 16);
  const r = (n >> 16) & 255, g = (n >> 8) & 255, b = n & 255;
  return 0.299 * r + 0.587 * g + 0.114 * b < 72 ? "#ededed" : `#${hex}`;
}

await mkdir("public/icons", { recursive: true });
const made = [];

for (const [id, name] of Object.entries(simple)) {
  const icon = si[`si${name}`];
  if (!icon) { console.log("no simple-icon", id); continue; }
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" role="img" aria-label="${icon.title}"><path fill="${ink(icon.hex)}" d="${icon.path}"/></svg>\n`;
  await writeFile(`public/icons/${id}.svg`, svg);
  made.push(id);
}

const list = await (await fetch("https://api.svgl.app")).json();
const byTitle = new Map(list.map((entry) => [entry.title.toLowerCase(), entry]));
for (const [id, title] of Object.entries(svgl)) {
  const entry = byTitle.get(title.toLowerCase());
  if (!entry) { console.log("no svgl entry", id); continue; }
  let route = entry.route;
  if (typeof route === "object") route = route.dark ?? route.light;
  const res = await fetch(route);
  if (!res.ok) { console.log("svgl fetch failed", id); continue; }
  await writeFile(`public/icons/${id}.svg`, await res.text());
  if (!made.includes(id)) made.push(id);
}

for (const id of existing) {
  if (!existsSync(`public/logos/${id}.svg`)) continue;
  await copyFile(`public/logos/${id}.svg`, `public/icons/${id}.svg`);
  made.push(id);
}

made.sort();
await writeFile(
  "src/icons.generated.ts",
  `// Generated by scripts/build-icons.mjs. Do not edit.\nexport const iconIds: ReadonlySet<string> = new Set(${JSON.stringify(made)});\n`,
);
console.log(`${made.length} icons`);
